version: "3.9"

networks:
    db-net:

services:

    db:
        image: redis
        container_name: db-dev-redis
        hostname: db
        ports:
            - 6379
        networks:
            - db-net

    api:
        image: node
        container_name: api-redis-livestream
        hostname: api
        # ports:
        #     - 8000:8000
        networks:
            - db-net
        volumes:
            - ./:/app
        working_dir: /app
        environment:
            - DB_HOST=db
            - DB_PORT=6379
        command: npm start
        depends_on:
            - db

    app:
        image: nginx
        container_name: app-logger
        hostname: app
        ports:
            - 8080:80
            - 8090:8090
        networks:
            - db-net
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/00_nginx.conf
            - ./www:/usr/share/nginx/html
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        command: [nginx-debug, '-g', 'daemon off;']
        depends_on:
            - db
            - api